/**
 * Comprehensive Fallback Exercise Catalog
 * Used when YMOVE_API_KEY is not configured or during offline development.
 */

import { Exercise } from './types';

export const FALLBACK_EXERCISES: Exercise[] = [
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    slug: 'barbell-bench-press',
    muscleGroups: ['Chest', 'Arms', 'Shoulders'],
    targetMuscles: ['Pectoralis Major (Mid/Lower Chest)'],
    secondaryMuscles: ['Triceps Brachii', 'Anterior Deltoid'],
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    exerciseType: 'Strength / Compound',
    instructions: [
      'Lie flat on the bench with your eyes directly under the racked barbell.',
      'Grip the bar slightly wider than shoulder-width with a firm, pronated grip and wrap your thumbs.',
      'Retract your scapulae (pull shoulder blades down and together) and plant both feet flat on the floor.',
      'Unrack the bar and stabilize it directly over your mid-chest with arms extended.',
      'Inhale and lower the bar in a controlled diagonal bar path until it lightly touches your sternum.',
      'Drive your feet into the floor, flare lats, and press the bar explosively back to starting lockout position while exhaling.',
    ],
    steps: [
      'Set up with 5 points of contact: head, upper back, glutes, and both feet.',
      'Unrack with locked wrists and braced core.',
      'Lower under 2-3s control to lower-sternum.',
      'Press up with maximum velocity along J-curve path.',
    ],
    formCues: [
      'Keep your wrists stacked directly over your elbows.',
      'Tuck elbows at roughly 45 to 70 degrees from torso, avoiding 90 degree flaring.',
      'Maintain continuous leg drive and glute tension throughout the repetition.',
    ],
    commonMistakes: [
      'Bouncing the bar off the ribcage instead of controlled touch.',
      'Flaring elbows out at 90 degrees which increases shoulder impingement risk.',
      'Lifting glutes off the bench to force heavier loads.',
    ],
    breathing: 'Inhale deeply and brace your core at the top. Hold during descent, and exhale powerfully as you press through the sticking point.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    slug: 'incline-dumbbell-press',
    muscleGroups: ['Chest', 'Shoulders', 'Arms'],
    targetMuscles: ['Clavicular Pectoralis (Upper Chest)'],
    secondaryMuscles: ['Anterior Deltoids', 'Triceps'],
    equipment: 'Dumbbell',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy / Compound',
    instructions: [
      'Adjust an incline bench between 30 and 45 degrees.',
      'Sit back with a dumbbell resting on each knee, then kick them up to shoulder height as you lie back.',
      'Keep shoulder blades pinched together with a slight arch in your mid-back.',
      'Lower the dumbbells with elbows angled inward until you feel a deep stretch in the upper chest.',
      'Press the dumbbells upwards and slightly inward without clanking them together at the apex.',
    ],
    formCues: [
      'Keep the bench incline moderate (30°) to prioritize upper pecs over front deltoids.',
      'Control the eccentric lowering phase for 3 seconds.',
      'Squeeze chest at the top without unlocking scapular retraction.',
    ],
    commonMistakes: [
      'Setting bench too high (>45 degrees) which shifts workload to anterior delts.',
      'Clanking weights at the top which relieves muscular tension.',
    ],
    breathing: 'Inhale as dumbbells descend; exhale forcefully as you drive weights upwards.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'standing-overhead-press',
    name: 'Standing Overhead Barbell Press (OHP)',
    slug: 'standing-overhead-press',
    muscleGroups: ['Shoulders', 'Arms', 'Core'],
    targetMuscles: ['Anterior & Lateral Deltoids'],
    secondaryMuscles: ['Triceps Brachii', 'Upper Trapezius', 'Core Stabilizers'],
    equipment: 'Barbell',
    difficulty: 'Advanced',
    exerciseType: 'Strength / Overhead Compound',
    instructions: [
      'Set the bar at mid-chest height. Grip just outside shoulder width with forearms perpendicular to the floor.',
      'Unrack and take two small steps back. Squeeze glutes and brace your abdomen.',
      'Tilt your head slightly back so the bar clears your chin.',
      'Press the bar in a vertical trajectory directly over the crown of your head, shrugging your traps slightly at lockout.',
      'Return under control to the front rack position at collarbone height.',
    ],
    formCues: [
      'Keep glutes squeezed tight to prevent lower back hyperextension.',
      'Pull your head forward through the "window" once the bar clears your forehead.',
      'Keep wrists straight with knuckles facing the ceiling.',
    ],
    commonMistakes: [
      'Leaning back excessively to convert the lift into an incline bench press.',
      'Pressing the bar forward around the head instead of tucking chin.',
    ],
    breathing: 'Inhale into your diaphragm and brace core before initiating the press. Exhale at top lockout.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'cable-chest-fly',
    name: 'High-to-Low Cable Chest Fly',
    slug: 'cable-chest-fly',
    muscleGroups: ['Chest'],
    targetMuscles: ['Sternal & Lower Pectoralis Major'],
    secondaryMuscles: ['Anterior Deltoids', 'Biceps Short Head'],
    equipment: 'Cable',
    difficulty: 'Beginner',
    exerciseType: 'Isolation / Hypertrophy',
    instructions: [
      'Position pulleys at the highest setting and attach D-handles.',
      'Grab handles with an overhand grip and take one step forward into a staggered stance.',
      'With a slight bend in your elbows, pull the cables down and across your body until your hands meet in front of your waist.',
      'Pause for a 1-second peak contraction, then slowly allow cables to open back up under control.',
    ],
    formCues: [
      'Maintain fixed elbow bend throughout the entire motion (do not turn into a press).',
      'Imagine hugging a large tree to ensure smooth arc movement.',
    ],
    commonMistakes: [
      'Using too much weight and pressing with triceps instead of flying with chest.',
      'Letting shoulders shrug upward during the eccentric stretch.',
    ],
    breathing: 'Exhale during the concentric sweep; inhale as arms spread open for a deep chest stretch.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'barbell-bicep-curl',
    name: 'Standing Barbell Bicep Curl',
    slug: 'barbell-bicep-curl',
    muscleGroups: ['Arms'],
    targetMuscles: ['Biceps Brachii (Short & Long Head)'],
    secondaryMuscles: ['Brachialis', 'Brachioradialis', 'Forearm Flexors'],
    equipment: 'Barbell',
    difficulty: 'Beginner',
    exerciseType: 'Isolation',
    instructions: [
      'Stand upright holding a barbell with a shoulder-width underhand (supinated) grip.',
      'Pin your elbows against your ribcage and stabilize your shoulders.',
      'Curl the bar upwards by contracting biceps while keeping your upper arms stationary.',
      'Squeeze peak contraction at the top for a count of 1, then lower under a 3-second negative.',
    ],
    formCues: [
      'Keep elbows pinned in line with your hips.',
      'Avoid swinging your hips or using momentum from lower back.',
    ],
    commonMistakes: [
      'Swinging the torso backward to hoist the barbell up.',
      'Letting elbows drift forward, which shifts tension to anterior delts.',
    ],
    breathing: 'Exhale as you curl the weight; inhale as you lower the barbell.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'dumbbell-hammer-curl',
    name: 'Standing Dumbbell Hammer Curl',
    slug: 'dumbbell-hammer-curl',
    muscleGroups: ['Arms'],
    targetMuscles: ['Brachialis & Brachioradialis (Arm Thickness)'],
    secondaryMuscles: ['Biceps Brachii Long Head'],
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    exerciseType: 'Isolation',
    instructions: [
      'Stand with dumbbells in hands using a neutral grip (palms facing inward toward each other).',
      'Keep your core braced and shoulders rolled back.',
      'Curl dumbbells simultaneously or alternating towards shoulder level while maintaining neutral wrist orientation.',
      'Lower with control back to full arm extension.',
    ],
    formCues: [
      'Maintain firm neutral grip throughout the range of motion.',
      'Control the bottom stretch without hyperextending elbows.',
    ],
    commonMistakes: [
      'Pronating or supinating wrists mid-rep.',
      'Rocking back and forth during heavy sets.',
    ],
    breathing: 'Exhale during the curl; inhale smoothly during lowering.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    slug: 'barbell-back-squat',
    muscleGroups: ['Legs', 'Core'],
    targetMuscles: ['Quadriceps Femoris', 'Gluteus Maximus'],
    secondaryMuscles: ['Hamstrings', 'Adductors', 'Erector Spinae'],
    equipment: 'Barbell',
    difficulty: 'Advanced',
    exerciseType: 'Strength / Lower Body Compound',
    instructions: [
      'Step under the bar resting it across upper traps (high bar) or rear delts (low bar).',
      'Unrack, take two steps back, and set feet shoulder-width apart with toes turned out 15-30 degrees.',
      'Inhale deeply, brace your core, and initiate by sitting back and pushing knees out.',
      'Descend until thighs are at least parallel to the floor.',
      'Drive upward through mid-foot and heels, maintaining a rigid neutral spine.',
    ],
    formCues: [
      'Push knees outward in line with toes.',
      'Keep chest tall and maintain abdominal intra-abdominal pressure (Valsalva).',
    ],
    commonMistakes: [
      'Knees collapsing inward (valgus fault) during the concentric ascent.',
      'Rounding the lumbar spine in the bottom hole (butt wink).',
    ],
    breathing: 'Big diaphragmatic breath and 360-degree abdominal brace at top; hold during descent, exhale past sticking point.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift (RDL)',
    slug: 'romanian-deadlift',
    muscleGroups: ['Legs', 'Back'],
    targetMuscles: ['Hamstrings (Biceps Femoris)', 'Gluteus Maximus'],
    secondaryMuscles: ['Erector Spinae', 'Latissimus Dorsi', 'Forearms'],
    equipment: 'Dumbbell',
    difficulty: 'Intermediate',
    exerciseType: 'Posterior Chain / Hypertrophy',
    instructions: [
      'Stand holding dumbbells against the front of your thighs with a slight bend in your knees.',
      'Hinge strictly at your hips, sending your pelvis backwards as if closing a door with your glutes.',
      'Trace the dumbbells down along your shins until you feel a deep hamstring stretch around mid-shin level.',
      'Contract glutes and hamstrings to drive your hips forward back to full standing position.',
    ],
    formCues: [
      'Keep knee angle fixed (this is a hip hinge, not a squat).',
      'Keep dumbbells close to legs to minimize spinal shear force.',
    ],
    commonMistakes: [
      'Rounding the lower back to get the weights lower.',
      'Bending knees excessively turning the movement into a squat.',
    ],
    breathing: 'Inhale at top and hinge down; exhale as you thrust hips forward to return.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'lat-pulldown',
    name: 'Wide-Grip Lat Pulldown',
    slug: 'lat-pulldown',
    muscleGroups: ['Back', 'Arms'],
    targetMuscles: ['Latissimus Dorsi'],
    secondaryMuscles: ['Biceps Brachii', 'Rhomboids', 'Rear Deltoids', 'Teres Major'],
    equipment: 'Cable',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy / Vertical Pull',
    instructions: [
      'Adjust thigh pad snug against your legs. Grip bar wider than shoulder-width with pronated grip.',
      'Sit down, arch upper back slightly, and look slightly upward towards the cable pulley.',
      'Pull bar down to upper chest by driving elbows down and back.',
      'Squeeze shoulder blades together at the bottom for 1 second, then slowly let the bar return to full arm stretch.',
    ],
    formCues: [
      'Lead the pull with your elbows, not your hands.',
      'Maintain slight upper back extension without excessive backward swing.',
    ],
    commonMistakes: [
      'Leaning back 45+ degrees and turning the movement into a horizontal row.',
      'Pulling the bar behind the neck which strains the cervical spine and rotator cuff.',
    ],
    breathing: 'Exhale as you pull the bar to your chest; inhale as you release to overhead stretch.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Knee / Leg Raise',
    slug: 'hanging-leg-raise',
    muscleGroups: ['Core'],
    targetMuscles: ['Rectus Abdominis (Lower Region)'],
    secondaryMuscles: ['Iliopsoas (Hip Flexors)', 'Obliques', 'Forearm Grip'],
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    exerciseType: 'Core Conditioning',
    instructions: [
      'Hang from a pull-up bar with an overhand grip and engage your shoulder lats to prevent swaying.',
      'Curl your pelvis upward and raise knees/legs toward your chest.',
      'Pause at the peak crunch for 1 second, focusing on abdominal contraction.',
      'Lower slowly under control without allowing your body to swing.',
    ],
    formCues: [
      'Focus on tilting the pelvis upward rather than simply flexing hips.',
      'Eliminate swinging momentum between reps.',
    ],
    commonMistakes: [
      'Using leg momentum / swinging like a pendulum.',
      'Arching lower back at the bottom of the movement.',
    ],
    breathing: 'Exhale as knees/legs raise up; inhale as you lower them.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    videoProvider: 'fallback',
  },
];
