/**
 * Comprehensive Fallback Exercise Catalog
 * Used when YMOVE_API_KEY is not configured or during offline development.
 * Provides broad multi-apparatus coverage (Bodyweight, Dumbbell, Barbell, Cable).
 */

import { Exercise } from './types';

export const FALLBACK_EXERCISES: Exercise[] = [
  // ── CHEST ──
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    slug: 'barbell-bench-press',
    muscleGroups: ['Chest', 'Arms', 'Shoulders'],
    targetMuscles: ['Pectoralis Major (Mid/Lower Chest)'],
    secondaryMuscles: ['Triceps Brachii', 'Anterior Deltoid'],
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    exerciseType: 'Strength / Compound',
    instructions: [
      'Lie flat on the bench with your eyes directly under the racked barbell.',
      'Grip the bar slightly wider than shoulder-width with a firm, pronated grip and wrap your thumbs.',
      'Retract your scapulae and plant both feet flat on the floor.',
      'Lower the bar in a controlled diagonal bar path until it lightly touches your sternum.',
      'Drive your feet into the floor and press the bar explosively back to starting lockout.',
    ],
    formCues: ['Keep wrists stacked over elbows.', 'Tuck elbows at 45 to 70 degrees from torso.'],
    commonMistakes: ['Bouncing the bar off the ribcage.', 'Flaring elbows out at 90 degrees.'],
    breathing: 'Inhale and brace at top. Lower under control, exhale powerfully as you press up.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    slug: 'incline-dumbbell-press',
    muscleGroups: ['Chest', 'Shoulders', 'Arms'],
    targetMuscles: ['Clavicular Pectoralis (Upper Chest)'],
    secondaryMuscles: ['Anterior Deltoids', 'Triceps'],
    equipment: 'Dumbbell',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy / Compound',
    instructions: [
      'Adjust an incline bench between 30 and 45 degrees.',
      'Kick dumbbells up to shoulder height as you lie back against the bench.',
      'Lower dumbbells until you feel a deep stretch in the upper chest.',
      'Press upward without clanking dumbbells together at the apex.',
    ],
    formCues: ['Keep bench incline at 30° to target upper pecs.', 'Control 3s eccentric negative.'],
    commonMistakes: ['Setting bench too high (>45°), overloading anterior deltoids.'],
    breathing: 'Inhale on descent; exhale forcefully on the upward drive.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'push-ups',
    name: 'Standard Push-Up',
    slug: 'push-ups',
    muscleGroups: ['Chest', 'Arms', 'Shoulders', 'Core'],
    targetMuscles: ['Pectoralis Major', 'Triceps Brachii'],
    secondaryMuscles: ['Anterior Deltoids', 'Rectus Abdominis'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Calisthenics / Compound',
    instructions: [
      'Assume a high plank position with hands slightly wider than shoulder width.',
      'Squeeze glutes and brace your core into a rigid straight line from head to heels.',
      'Lower your chest until it is an inch off the floor, keeping elbows tucked at 45 degrees.',
      'Push through full palms to extend arms and return to top plank.',
    ],
    formCues: ['Do not let hips sag.', 'Keep neck neutral, eyes looking slightly ahead of hands.'],
    commonMistakes: ['Flaring elbows out to T-shape.', 'Sagging hips or piking pelvis up.'],
    breathing: 'Inhale as you lower; exhale as you push the ground away.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'cable-chest-fly',
    name: 'High-to-Low Cable Chest Fly',
    slug: 'cable-chest-fly',
    muscleGroups: ['Chest'],
    targetMuscles: ['Sternal & Lower Pectoralis Major'],
    secondaryMuscles: ['Anterior Deltoids', 'Biceps Short Head'],
    equipment: 'Cable',
    difficulty: 'Beginner',
    exerciseType: 'Isolation / Hypertrophy',
    instructions: [
      'Position pulleys at chest height. Take one step forward into a staggered stance.',
      'With elbows slightly bent, sweep hands forward in a wide arc until they meet in front of your chest.',
      'Squeeze chest contraction for 1 second, then control the return stretch.',
    ],
    formCues: ['Maintain fixed elbow bend.', 'Lead with chest squeeze.'],
    commonMistakes: ['Turning fly into a press by excessively bending and extending elbows.'],
    breathing: 'Exhale on contraction; inhale on stretch.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },

  // ── BACK & LATS ──
  {
    id: 'lat-pulldown',
    name: 'Wide-Grip Lat Pulldown',
    slug: 'lat-pulldown',
    muscleGroups: ['Back', 'Arms'],
    targetMuscles: ['Latissimus Dorsi'],
    secondaryMuscles: ['Biceps Brachii', 'Rhomboids', 'Rear Deltoids'],
    equipment: 'Cable',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy / Vertical Pull',
    instructions: [
      'Sit with thighs locked under pads. Grip bar wider than shoulders.',
      'Pull bar down to upper clavicle by driving elbows down and back.',
      'Squeeze shoulder blades together at bottom for 1 second, then control the return.',
    ],
    formCues: ['Lead pull with elbows.', 'Avoid excessive backward lean.'],
    commonMistakes: ['Pulling bar behind the neck.', 'Using body momentum.'],
    breathing: 'Exhale on pull; inhale on stretch.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'dumbbell-bent-over-row',
    name: 'Dumbbell Bent-Over Row',
    slug: 'dumbbell-bent-over-row',
    muscleGroups: ['Back', 'Arms'],
    targetMuscles: ['Rhomboids', 'Latissimus Dorsi', 'Mid Trapezius'],
    secondaryMuscles: ['Biceps', 'Rear Deltoids', 'Erector Spinae'],
    equipment: 'Dumbbell',
    difficulty: 'Intermediate',
    exerciseType: 'Strength / Horizontal Pull',
    instructions: [
      'Hinge at hips to a 45-degree angle holding dumbbells with palms facing each other.',
      'Keep your spine neutral and core braced.',
      'Pull dumbbells toward your hips, driving elbows back and pinching shoulder blades.',
      'Lower with control under full stretch.',
    ],
    formCues: ['Pull towards hips rather than shoulders.', 'Keep lumbar spine braced.'],
    commonMistakes: ['Rounding the lower back.', 'Shrugging shoulders upward.'],
    breathing: 'Exhale as you row; inhale as you lower weights.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'pull-ups',
    name: 'Bodyweight Pull-Up',
    slug: 'pull-ups',
    muscleGroups: ['Back', 'Arms', 'Core'],
    targetMuscles: ['Latissimus Dorsi', 'Teres Major'],
    secondaryMuscles: ['Biceps Brachii', 'Brachialis', 'Lower Traps'],
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    exerciseType: 'Calisthenics / Vertical Pull',
    instructions: [
      'Grip the pull-up bar with hands just outside shoulder-width, palms facing away.',
      'Hang with arms extended and engage scapular depressors.',
      'Pull yourself upward until your chin clears the bar.',
      'Lower smoothly to full dead hang stretch.',
    ],
    formCues: ['Chest up, drive elbows down to ribs.', 'Do not kick or swing legs.'],
    commonMistakes: ['Kipping or swinging.', 'Half reps omitting full extension.'],
    breathing: 'Exhale on ascent; inhale on descent.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'bird-dog',
    name: 'Quadruped Bird-Dog (Spine Safe)',
    slug: 'bird-dog',
    muscleGroups: ['Back', 'Core'],
    targetMuscles: ['Erector Spinae', 'Gluteus Maximus', 'Transverse Abdominis'],
    secondaryMuscles: ['Deltoids', 'Hamstrings'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Core / Spine Rehab',
    instructions: [
      'Start on all fours with hands under shoulders and knees under hips.',
      'Brace core, then simultaneously extend right arm forward and left leg backward.',
      'Hold for 2 seconds at full parallel extension without tilting hips.',
      'Return to center and switch to opposite side.',
    ],
    formCues: ['Keep hips level with the ground.', 'Reach long through fingers and heel.'],
    commonMistakes: ['Hyperextending spine or rotating pelvis.'],
    breathing: 'Smooth, rhythmic diaphragmatic breathing.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },

  // ── SHOULDERS ──
  {
    id: 'standing-overhead-press',
    name: 'Standing Overhead Barbell Press',
    slug: 'standing-overhead-press',
    muscleGroups: ['Shoulders', 'Arms', 'Core'],
    targetMuscles: ['Anterior & Lateral Deltoids'],
    secondaryMuscles: ['Triceps Brachii', 'Upper Trapezius'],
    equipment: 'Barbell',
    difficulty: 'Advanced',
    exerciseType: 'Strength / Overhead Compound',
    instructions: [
      'Grip barbell at shoulder width in front rack position.',
      'Brace core and glutes, press the bar vertically overhead.',
      'Lock out with head through the window at top.',
      'Lower with control back to collarbone.',
    ],
    formCues: ['Squeeze glutes to protect lower back.', 'Vertical bar path.'],
    commonMistakes: ['Leaning backward excessively.', 'Pressing bar in front of head.'],
    breathing: 'Inhale and brace at bottom; exhale at lockout.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    slug: 'dumbbell-lateral-raise',
    muscleGroups: ['Shoulders'],
    targetMuscles: ['Lateral Deltoids (Side Delts)'],
    secondaryMuscles: ['Supraspinatus', 'Trapezius'],
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    exerciseType: 'Isolation',
    instructions: [
      'Stand with dumbbells at sides with a slight forward lean and slight elbow bend.',
      'Raise dumbbells out to sides until arms are parallel to the floor.',
      'Lead with elbows and pour pitcher slightly at apex.',
      'Lower under 2-second control.',
    ],
    formCues: ['Keep pinkies slightly higher than thumbs.', 'Avoid shrugging traps.'],
    commonMistakes: ['Swinging torso to generate momentum.', 'Lifting hands higher than elbows.'],
    breathing: 'Exhale on lift; inhale on descent.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push-Up (Bodyweight Shoulder Press)',
    slug: 'pike-push-up',
    muscleGroups: ['Shoulders', 'Arms', 'Core'],
    targetMuscles: ['Anterior & Lateral Deltoids', 'Triceps'],
    secondaryMuscles: ['Upper Chest', 'Serratus Anterior'],
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    exerciseType: 'Calisthenics / Overhead Press',
    instructions: [
      'Start in a push-up position, then walk feet forward into an inverted V-shape (pike).',
      'Lower top of head toward the floor between your hands.',
      'Press through shoulders to push back up into the pike position.',
    ],
    formCues: ['Keep hips high.', 'Elbows tuck at 45 degrees.'],
    commonMistakes: ['Allowing hips to drop into a standard push-up.'],
    breathing: 'Inhale as head descends; exhale as you push up.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },

  // ── LEGS & GLUTES ──
  {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    slug: 'barbell-back-squat',
    muscleGroups: ['Legs', 'Quads', 'Core'],
    targetMuscles: ['Quadriceps Femoris', 'Gluteus Maximus'],
    secondaryMuscles: ['Hamstrings', 'Adductors', 'Erector Spinae'],
    equipment: 'Barbell',
    difficulty: 'Advanced',
    exerciseType: 'Strength / Lower Body Compound',
    instructions: [
      'Rest bar across upper traps. Step back with feet shoulder-width, toes turned 15-30 degrees.',
      'Inhale deeply, brace core, and sit down between your hips pushing knees out.',
      'Descend to parallel or below.',
      'Drive forcefully up through mid-foot.',
    ],
    formCues: ['Knees track over toes.', 'Maintain proud chest.'],
    commonMistakes: ['Knee valgus collapse.', 'Heels lifting off floor.'],
    breathing: 'Brace at top; hold on descent; exhale past sticking point.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'bodyweight-squat',
    name: 'Air Squat (Bodyweight Squat)',
    slug: 'bodyweight-squat',
    muscleGroups: ['Legs', 'Quads', 'Glutes'],
    targetMuscles: ['Quadriceps', 'Gluteus Maximus'],
    secondaryMuscles: ['Hamstrings', 'Calves', 'Core'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Calisthenics / Functional',
    instructions: [
      'Stand with feet shoulder-width apart, arms extended in front for balance.',
      'Sit hips down and back until thighs reach parallel.',
      'Drive through heels to stand fully upright.',
    ],
    formCues: ['Keep weight centered over mid-foot.', 'Chest up, knees tracking out.'],
    commonMistakes: ['Rounding forward.', 'Not reaching parallel depth.'],
    breathing: 'Inhale down; exhale up.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift (RDL)',
    slug: 'romanian-deadlift',
    muscleGroups: ['Legs', 'Hamstrings', 'Back'],
    targetMuscles: ['Hamstrings (Biceps Femoris)', 'Gluteus Maximus'],
    secondaryMuscles: ['Erector Spinae', 'Latissimus Dorsi'],
    equipment: 'Dumbbell',
    difficulty: 'Intermediate',
    exerciseType: 'Posterior Chain / Hypertrophy',
    instructions: [
      'Hold dumbbells against thighs with soft knees.',
      'Hinge hips backward, tracing weights down shins until hamstring stretch.',
      'Squeeze glutes and thrust hips forward to return.',
    ],
    formCues: ['Push hips back (closing a car door).', 'Keep spine neutral.'],
    commonMistakes: ['Squatting instead of hinging.', 'Rounding lower back.'],
    breathing: 'Inhale down; exhale as hips return forward.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'glute-bridge',
    name: 'Bodyweight Glute Bridge (Knee Friendly)',
    slug: 'glute-bridge',
    muscleGroups: ['Legs', 'Glutes', 'Hamstrings'],
    targetMuscles: ['Gluteus Maximus'],
    secondaryMuscles: ['Hamstrings', 'Erector Spinae'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Rehab / Posterior Chain',
    instructions: [
      'Lie flat on back with knees bent and feet flat on floor hip-width apart.',
      'Drive through heels and squeeze glutes to elevate hips into a straight bridge line.',
      'Hold top squeeze for 2 seconds, then lower under control.',
    ],
    formCues: ['Drive through heels.', 'Do not hyperextend lower back at top.'],
    commonMistakes: ['Arching lumbar spine instead of extending hips.'],
    breathing: 'Exhale on hip lift; inhale on lowering.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'walking-lunge',
    name: 'Walking Bodyweight Lunge',
    slug: 'walking-lunge',
    muscleGroups: ['Legs', 'Quads', 'Glutes'],
    targetMuscles: ['Quadriceps', 'Gluteus Medius & Maximus'],
    secondaryMuscles: ['Hamstrings', 'Calves', 'Core'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Functional / Unilateral',
    instructions: [
      'Take a controlled stride forward and lower hips until both knees are at 90 degrees.',
      'Drive through front heel to step through into the next stride.',
    ],
    formCues: ['Keep torso upright.', 'Front knee tracks over second toe.'],
    commonMistakes: ['Front heel coming off ground.', 'Torso collapsing forward.'],
    breathing: 'Rhythmic breathing with each step.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },

  // ── ARMS (BICEPS & TRICEPS) ──
  {
    id: 'dumbbell-hammer-curl',
    name: 'Standing Dumbbell Hammer Curl',
    slug: 'dumbbell-hammer-curl',
    muscleGroups: ['Arms'],
    targetMuscles: ['Brachialis & Brachioradialis'],
    secondaryMuscles: ['Biceps Brachii'],
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    exerciseType: 'Isolation',
    instructions: [
      'Hold dumbbells with a neutral palms-facing-in grip.',
      'Curl dumbbells toward shoulders keeping elbows pinned at your sides.',
      'Lower with control under a 2-second negative.',
    ],
    formCues: ['Keep elbows pinned.', 'Avoid swinging hips.'],
    commonMistakes: ['Using momentum from back.'],
    breathing: 'Exhale up; inhale down.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'tricep-dips',
    name: 'Bench / Chair Tricep Dip',
    slug: 'tricep-dips',
    muscleGroups: ['Arms', 'Chest'],
    targetMuscles: ['Triceps Brachii (Lateral & Medial Head)'],
    secondaryMuscles: ['Anterior Deltoid', 'Pectoralis Minor'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Calisthenics / Isolation',
    instructions: [
      'Place hands on edge of bench behind you, fingers facing forward.',
      'Lower hips by bending elbows to 90 degrees.',
      'Press through palms to extend arms and return to top.',
    ],
    formCues: ['Keep back close to the bench.', 'Keep shoulders depressed.'],
    commonMistakes: ['Shrugging shoulders up toward ears.'],
    breathing: 'Inhale down; exhale as you push up.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },

  // ── CORE & STABILITY ──
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Knee / Leg Raise',
    slug: 'hanging-leg-raise',
    muscleGroups: ['Core'],
    targetMuscles: ['Rectus Abdominis (Lower Region)'],
    secondaryMuscles: ['Iliopsoas', 'Obliques', 'Forearm Grip'],
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    exerciseType: 'Core Conditioning',
    instructions: [
      'Hang from a pull-up bar with overhand grip and engaged shoulders.',
      'Curl pelvis upward and raise knees/legs toward chest.',
      'Hold peak crunch for 1 second, then lower slowly without swinging.',
    ],
    formCues: ['Tilt pelvis upward.', 'Eliminate swinging momentum.'],
    commonMistakes: ['Swinging like a pendulum.'],
    breathing: 'Exhale as legs raise; inhale as they lower.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'plank',
    name: 'Standard Forearm Plank',
    slug: 'plank',
    muscleGroups: ['Core'],
    targetMuscles: ['Transverse Abdominis', 'Rectus Abdominis'],
    secondaryMuscles: ['Gluteus Maximus', 'Deltoids', 'Quadriceps'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Isometric / Stability',
    instructions: [
      'Rest on forearms with elbows directly under shoulders.',
      'Squeeze glutes and pull navel to spine, creating a straight plank line.',
      'Hold position with steady breathing without letting hips drop or pike.',
    ],
    formCues: ['Tuck pelvis slightly (posterior tilt).', 'Push ground away through forearms.'],
    commonMistakes: ['Sagging lower back.', 'Holding breath.'],
    breathing: 'Continuous shallow diaphragmatic breathing.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug (Lumbar Spine Safe)',
    slug: 'dead-bug',
    muscleGroups: ['Core'],
    targetMuscles: ['Transverse Abdominis', 'Internal Obliques'],
    secondaryMuscles: ['Hip Flexors', 'Deltoids'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Core / Rehab',
    instructions: [
      'Lie on back with arms extended toward ceiling and hips/knees bent at 90 degrees.',
      'Press lower back flat into the floor.',
      'Slowly lower right arm and left leg toward floor simultaneously.',
      'Return to starting position and alternate sides.',
    ],
    formCues: ['Keep lower back glued to the floor.', 'Move slowly with control.'],
    commonMistakes: ['Lower back arching off the floor.'],
    breathing: 'Exhale as limbs extend; inhale as they return.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },

  // ── MOBILITY & RECOVERY ──
  {
    id: 'world-greatest-stretch',
    name: 'World&apos;s Greatest Stretch',
    slug: 'world-greatest-stretch',
    muscleGroups: ['Legs', 'Back', 'Core', 'Shoulders'],
    targetMuscles: ['Hip Flexors', 'Thoracic Spine', 'Hamstrings', 'Glutes'],
    secondaryMuscles: ['Adductors', 'Deltoids'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Mobility / Full Body Dynamic',
    instructions: [
      'Step forward into a deep lunge with both hands on the floor inside front foot.',
      'Drop inside elbow toward the floor for a deep hip stretch.',
      'Rotate torso toward front knee and reach arm vertically toward the ceiling.',
      'Return and push hips back to stretch front hamstring.',
    ],
    formCues: ['Keep back leg active and knee off floor.', 'Follow hand with eyes during rotation.'],
    commonMistakes: ['Rushing through rotation without full thoracic extension.'],
    breathing: 'Exhale into the reach; inhale back to center.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/exercise-demo.mp4',
    videoProvider: 'fallback',
  },
];
