import { FoodCategory, FoodItem } from './types';

export const FOOD_CATEGORIES: FoodCategory[] = [
  { id: 'all', name: 'All Foods', icon: '🍽️', description: 'Complete catalog' },
  { id: 'indian_breads', name: 'Roti & Breads', icon: '🫓', description: 'Rotis, parathas, naans' },
  { id: 'rice_grains', name: 'Rice & Grains', icon: '🍚', description: 'Rice, poha, upma, oats' },
  { id: 'dal_legumes', name: 'Dal & Legumes', icon: '🍲', description: 'Lentils, chana, rajma' },
  { id: 'vegetables_sabzi', name: 'Vegetables & Sabzi', icon: '🥦', description: 'Cooked sabzis, raw salads' },
  { id: 'protein', name: 'Protein & Eggs', icon: '🍗', description: 'Eggs, chicken, fish, paneer, tofu' },
  { id: 'dairy', name: 'Dairy & Curd', icon: '🥛', description: 'Curd, milk, chaas, paneer' },
  { id: 'fruits', name: 'Fruits', icon: '🍎', description: 'Fresh whole fruits' },
  { id: 'breakfast', name: 'Breakfast Items', icon: '🥞', description: 'Idli, dosa, chilla, paratha' },
  { id: 'snacks_nuts', name: 'Snacks & Nuts', icon: '🥜', description: 'Makhana, roasted chana, almonds' },
  { id: 'beverages', name: 'Beverages', icon: '☕', description: 'Tea, coffee, coconut water' },
];

export const INITIAL_FOOD_CATALOG: FoodItem[] = [
  // ── ROTI & BREADS ────────────────────────────────────────────────────────
  {
    id: 'food_roti_phulka',
    name: 'Roti / Phulka (Whole Wheat)',
    hindiName: 'रोटी / फुल्का',
    aliases: ['roti', 'phulka', 'chapati', 'wheat roti', 'roti without oil'],
    categoryId: 'indian_breads',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 medium piece (approx. 35-40g)',
    baseNutrition: { calories: 104, protein: 3.1, carbs: 22.4, fat: 0.5, fiber: 2.8 },
    allowedNutritionRange: {
      calories: { min: 80, max: 140 },
      protein: { min: 2.0, max: 4.5 },
      carbs: { min: 16.0, max: 28.0 },
      fat: { min: 0.2, max: 3.0 },
    },
    dietaryFlags: 'vegan',
    allergens: ['gluten'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    sourceReference: 'IFCT Code A001',
    verified: true,
    active: true,
  },
  {
    id: 'food_tandoori_roti',
    name: 'Tandoori Roti (Wheat)',
    hindiName: 'तन्दूरी रोटी',
    aliases: ['tandoori roti', 'plain tandoori roti'],
    categoryId: 'indian_breads',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 large piece (approx. 50g)',
    baseNutrition: { calories: 130, protein: 4.2, carbs: 27.5, fat: 0.6, fiber: 3.2 },
    allowedNutritionRange: {
      calories: { min: 100, max: 170 },
      protein: { min: 3.0, max: 5.5 },
      carbs: { min: 20.0, max: 34.0 },
      fat: { min: 0.3, max: 3.5 },
    },
    dietaryFlags: 'vegan',
    allergens: ['gluten'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_missi_roti',
    name: 'Missi Roti (Besan & Wheat)',
    hindiName: 'मिस्सी रोटी',
    aliases: ['missi roti', 'besan roti', 'gram flour roti'],
    categoryId: 'indian_breads',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 medium piece (approx. 45g)',
    baseNutrition: { calories: 142, protein: 5.6, carbs: 23.8, fat: 2.8, fiber: 3.9 },
    allowedNutritionRange: {
      calories: { min: 110, max: 190 },
      protein: { min: 4.0, max: 7.5 },
      carbs: { min: 18.0, max: 30.0 },
      fat: { min: 1.0, max: 6.0 },
    },
    dietaryFlags: 'vegan',
    allergens: ['gluten'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_bajra_roti',
    name: 'Bajra Roti (Pearl Millet)',
    hindiName: 'बाजरे की रोटी',
    aliases: ['bajra roti', 'bajre ki roti', 'millet roti'],
    categoryId: 'indian_breads',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 medium piece (approx. 50g)',
    baseNutrition: { calories: 135, protein: 3.8, carbs: 24.5, fat: 2.2, fiber: 4.1 },
    allowedNutritionRange: {
      calories: { min: 105, max: 180 },
      protein: { min: 2.5, max: 5.0 },
      carbs: { min: 19.0, max: 32.0 },
      fat: { min: 1.0, max: 5.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_jowar_roti',
    name: 'Jowar Roti (Sorghum)',
    hindiName: 'ज्वार की रोटी',
    aliases: ['jowar roti', 'sorghum roti', 'jowar bhakri'],
    categoryId: 'indian_breads',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 medium piece (approx. 45g)',
    baseNutrition: { calories: 122, protein: 3.2, carbs: 25.1, fat: 1.0, fiber: 3.6 },
    allowedNutritionRange: {
      calories: { min: 95, max: 160 },
      protein: { min: 2.2, max: 4.8 },
      carbs: { min: 19.0, max: 32.0 },
      fat: { min: 0.4, max: 3.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_multigrain_roti',
    name: 'Multigrain Roti',
    hindiName: 'मल्टीग्रेन रोटी',
    aliases: ['multigrain roti', 'mixed flour roti'],
    categoryId: 'indian_breads',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 medium piece (approx. 40g)',
    baseNutrition: { calories: 118, protein: 4.1, carbs: 21.8, fat: 1.4, fiber: 3.8 },
    allowedNutritionRange: {
      calories: { min: 90, max: 160 },
      protein: { min: 3.0, max: 6.0 },
      carbs: { min: 16.0, max: 28.0 },
      fat: { min: 0.5, max: 4.0 },
    },
    dietaryFlags: 'vegan',
    allergens: ['gluten'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_plain_paratha',
    name: 'Plain Paratha (Ghee/Oil)',
    hindiName: 'सादा पराठा',
    aliases: ['plain paratha', 'paratha with ghee', 'tawa paratha'],
    categoryId: 'indian_breads',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 medium piece (approx. 60g)',
    baseNutrition: { calories: 235, protein: 4.2, carbs: 29.0, fat: 11.2, fiber: 3.0 },
    allowedNutritionRange: {
      calories: { min: 180, max: 320 },
      protein: { min: 3.0, max: 6.0 },
      carbs: { min: 22.0, max: 36.0 },
      fat: { min: 6.0, max: 18.0 },
    },
    dietaryFlags: 'veg',
    allergens: ['gluten', 'dairy'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_aloo_paratha',
    name: 'Aloo Paratha',
    hindiName: 'आलू पराठा',
    aliases: ['aloo paratha', 'potato paratha'],
    categoryId: 'indian_breads',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 medium stuffed piece (approx. 100g)',
    baseNutrition: { calories: 290, protein: 5.4, carbs: 42.0, fat: 11.5, fiber: 4.2 },
    allowedNutritionRange: {
      calories: { min: 220, max: 380 },
      protein: { min: 4.0, max: 8.0 },
      carbs: { min: 32.0, max: 52.0 },
      fat: { min: 6.0, max: 18.0 },
    },
    dietaryFlags: 'veg',
    allergens: ['gluten', 'dairy'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_paneer_paratha',
    name: 'Paneer Paratha',
    hindiName: 'पनीर पराठा',
    aliases: ['paneer paratha', 'cottage cheese paratha'],
    categoryId: 'indian_breads',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 medium stuffed piece (approx. 110g)',
    baseNutrition: { calories: 330, protein: 11.8, carbs: 36.5, fat: 15.2, fiber: 3.8 },
    allowedNutritionRange: {
      calories: { min: 250, max: 420 },
      protein: { min: 8.0, max: 16.0 },
      carbs: { min: 28.0, max: 45.0 },
      fat: { min: 9.0, max: 22.0 },
    },
    dietaryFlags: 'veg',
    allergens: ['gluten', 'dairy'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },

  // ── RICE & GRAINS ────────────────────────────────────────────────────────
  {
    id: 'food_steamed_rice',
    name: 'Steamed White Basmati Rice',
    hindiName: 'सफेद चावल',
    aliases: ['white rice', 'steamed rice', 'chawal', 'boiled rice', 'basmati rice'],
    categoryId: 'rice_grains',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 katori / bowl cooked (approx. 150g)',
    baseNutrition: { calories: 195, protein: 3.9, carbs: 43.5, fat: 0.4, fiber: 0.6 },
    allowedNutritionRange: {
      calories: { min: 140, max: 260 },
      protein: { min: 2.5, max: 5.5 },
      carbs: { min: 32.0, max: 55.0 },
      fat: { min: 0.1, max: 2.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_brown_rice',
    name: 'Cooked Brown Rice',
    hindiName: 'ब्राउन राइस',
    aliases: ['brown rice', 'unpolished rice'],
    categoryId: 'rice_grains',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 katori / bowl cooked (approx. 150g)',
    baseNutrition: { calories: 168, protein: 3.8, carbs: 35.2, fat: 1.4, fiber: 2.8 },
    allowedNutritionRange: {
      calories: { min: 130, max: 220 },
      protein: { min: 2.8, max: 5.2 },
      carbs: { min: 28.0, max: 44.0 },
      fat: { min: 0.8, max: 3.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_poha',
    name: 'Vegetable Poha',
    hindiName: 'पोहा',
    aliases: ['poha', 'flattened rice', 'kanda poha'],
    categoryId: 'rice_grains',
    servingUnit: 'plate',
    servingAmount: 1,
    servingDescription: '1 medium plate (approx. 150g)',
    baseNutrition: { calories: 245, protein: 4.8, carbs: 46.2, fat: 4.9, fiber: 3.1 },
    allowedNutritionRange: {
      calories: { min: 180, max: 320 },
      protein: { min: 3.5, max: 7.0 },
      carbs: { min: 35.0, max: 58.0 },
      fat: { min: 2.5, max: 9.0 },
    },
    dietaryFlags: 'vegan',
    allergens: ['peanuts'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_upma',
    name: 'Semolina Upma',
    hindiName: 'उपमा',
    aliases: ['upma', 'suji upma', 'rava upma'],
    categoryId: 'rice_grains',
    servingUnit: 'plate',
    servingAmount: 1,
    servingDescription: '1 medium plate (approx. 160g)',
    baseNutrition: { calories: 230, protein: 5.2, carbs: 41.5, fat: 5.1, fiber: 2.6 },
    allowedNutritionRange: {
      calories: { min: 170, max: 300 },
      protein: { min: 3.8, max: 7.5 },
      carbs: { min: 30.0, max: 52.0 },
      fat: { min: 2.5, max: 9.0 },
    },
    dietaryFlags: 'veg',
    allergens: ['gluten'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_oats_cooked',
    name: 'Rolled Oats (Water/Skim Milk)',
    hindiName: 'ओट्स',
    aliases: ['oats', 'porridge', 'oatmeal'],
    categoryId: 'rice_grains',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 medium bowl (approx. 40g dry cooked)',
    baseNutrition: { calories: 154, protein: 5.1, carbs: 27.4, fat: 2.6, fiber: 4.0 },
    allowedNutritionRange: {
      calories: { min: 120, max: 210 },
      protein: { min: 3.5, max: 8.0 },
      carbs: { min: 20.0, max: 35.0 },
      fat: { min: 1.5, max: 5.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'USDA FoodData Central',
    verified: true,
    active: true,
  },

  // ── DAL & LEGUMES ────────────────────────────────────────────────────────
  {
    id: 'food_moong_dal',
    name: 'Yellow Moong Dal (Cooked Tadka)',
    hindiName: 'मूंग दाल',
    aliases: ['moong dal', 'yellow dal', 'dal tadka', 'mung dal'],
    categoryId: 'dal_legumes',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 katori / bowl (approx. 150g)',
    baseNutrition: { calories: 148, protein: 8.5, carbs: 21.2, fat: 3.4, fiber: 5.2 },
    allowedNutritionRange: {
      calories: { min: 110, max: 210 },
      protein: { min: 6.5, max: 12.0 },
      carbs: { min: 16.0, max: 28.0 },
      fat: { min: 1.5, max: 7.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_toor_dal',
    name: 'Toor Dal / Arhar Dal (Tadka)',
    hindiName: 'अरहर दाल / तूर दाल',
    aliases: ['toor dal', 'arhar dal', 'dal fry'],
    categoryId: 'dal_legumes',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 katori / bowl (approx. 150g)',
    baseNutrition: { calories: 155, protein: 8.8, carbs: 22.0, fat: 3.6, fiber: 4.8 },
    allowedNutritionRange: {
      calories: { min: 120, max: 220 },
      protein: { min: 6.8, max: 12.5 },
      carbs: { min: 17.0, max: 30.0 },
      fat: { min: 1.8, max: 7.5 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_chana_masala',
    name: 'Chana Masala / Chole',
    hindiName: 'चना मसाला / छोले',
    aliases: ['chana', 'chole', 'chickpeas curry', 'white chana'],
    categoryId: 'dal_legumes',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 medium katori (approx. 150g)',
    baseNutrition: { calories: 210, protein: 9.6, carbs: 29.5, fat: 6.2, fiber: 7.4 },
    allowedNutritionRange: {
      calories: { min: 160, max: 280 },
      protein: { min: 7.0, max: 14.0 },
      carbs: { min: 22.0, max: 38.0 },
      fat: { min: 3.5, max: 11.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_rajma',
    name: 'Punjabi Rajma Curry (Kidney Beans)',
    hindiName: 'राजमा',
    aliases: ['rajma', 'red kidney beans curry', 'punjabi rajma'],
    categoryId: 'dal_legumes',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 medium katori (approx. 150g)',
    baseNutrition: { calories: 198, protein: 9.2, carbs: 28.6, fat: 5.4, fiber: 6.8 },
    allowedNutritionRange: {
      calories: { min: 150, max: 270 },
      protein: { min: 7.0, max: 13.0 },
      carbs: { min: 21.0, max: 37.0 },
      fat: { min: 3.0, max: 10.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_sprouted_moong',
    name: 'Sprouted Green Moong Salad',
    hindiName: 'अंकुरित मूंग',
    aliases: ['sprouts', 'moong sprouts', 'sprouted beans'],
    categoryId: 'dal_legumes',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 medium katori raw/steamed (approx. 100g)',
    baseNutrition: { calories: 105, protein: 7.2, carbs: 18.5, fat: 0.5, fiber: 4.8 },
    allowedNutritionRange: {
      calories: { min: 80, max: 140 },
      protein: { min: 5.5, max: 9.5 },
      carbs: { min: 14.0, max: 24.0 },
      fat: { min: 0.2, max: 2.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },

  // ── VEGETABLES & SABZI ───────────────────────────────────────────────────
  {
    id: 'food_aloo_gobi',
    name: 'Aloo Gobi Sabzi',
    hindiName: 'आलू गोभी',
    aliases: ['aloo gobi', 'potato cauliflower sabzi'],
    categoryId: 'vegetables_sabzi',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 medium katori (approx. 130g)',
    baseNutrition: { calories: 145, protein: 2.8, carbs: 21.4, fat: 5.6, fiber: 3.5 },
    allowedNutritionRange: {
      calories: { min: 110, max: 200 },
      protein: { min: 2.0, max: 4.5 },
      carbs: { min: 15.0, max: 28.0 },
      fat: { min: 3.0, max: 10.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_bhindi_masala',
    name: 'Bhindi Masala (Okra)',
    hindiName: 'भिंडी मसाला',
    aliases: ['bhindi', 'okra', 'ladyfinger sabzi'],
    categoryId: 'vegetables_sabzi',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 medium katori (approx. 120g)',
    baseNutrition: { calories: 118, protein: 2.4, carbs: 12.8, fat: 6.5, fiber: 3.8 },
    allowedNutritionRange: {
      calories: { min: 85, max: 165 },
      protein: { min: 1.8, max: 3.8 },
      carbs: { min: 9.0, max: 18.0 },
      fat: { min: 3.5, max: 11.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_palak_paneer',
    name: 'Palak Paneer',
    hindiName: 'पालक पनीर',
    aliases: ['palak paneer', 'spinach paneer'],
    categoryId: 'vegetables_sabzi',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 medium katori (approx. 150g)',
    baseNutrition: { calories: 240, protein: 12.5, carbs: 9.2, fat: 17.5, fiber: 3.6 },
    allowedNutritionRange: {
      calories: { min: 180, max: 320 },
      protein: { min: 9.0, max: 17.0 },
      carbs: { min: 6.0, max: 15.0 },
      fat: { min: 12.0, max: 24.0 },
    },
    dietaryFlags: 'veg',
    allergens: ['dairy'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_mixed_veg',
    name: 'Homestyle Mixed Vegetable Sabzi',
    hindiName: 'मिक्स वेज',
    aliases: ['mixed veg', 'mix vegetable', 'gobar matar gajar'],
    categoryId: 'vegetables_sabzi',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 medium katori (approx. 130g)',
    baseNutrition: { calories: 125, protein: 3.2, carbs: 16.5, fat: 5.2, fiber: 4.1 },
    allowedNutritionRange: {
      calories: { min: 90, max: 180 },
      protein: { min: 2.2, max: 5.0 },
      carbs: { min: 11.0, max: 23.0 },
      fat: { min: 2.8, max: 9.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_green_salad',
    name: 'Cucumber Tomato Onion Salad',
    hindiName: 'ककड़ी टमाटर सलाद',
    aliases: ['salad', 'green salad', 'kheera tamatar salad'],
    categoryId: 'vegetables_sabzi',
    servingUnit: 'plate',
    servingAmount: 1,
    servingDescription: '1 small plate (approx. 120g)',
    baseNutrition: { calories: 28, protein: 1.1, carbs: 5.6, fat: 0.2, fiber: 1.9 },
    allowedNutritionRange: {
      calories: { min: 18, max: 45 },
      protein: { min: 0.8, max: 2.0 },
      carbs: { min: 3.5, max: 9.0 },
      fat: { min: 0.1, max: 0.8 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },

  // ── DAIRY ────────────────────────────────────────────────────────────────
  {
    id: 'food_plain_curd',
    name: 'Plain Curd / Fresh Dahi',
    hindiName: 'दही',
    aliases: ['curd', 'dahi', 'plain yogurt'],
    categoryId: 'dairy',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 katori / bowl (approx. 120g)',
    baseNutrition: { calories: 86, protein: 4.2, carbs: 6.0, fat: 5.0, fiber: 0 },
    allowedNutritionRange: {
      calories: { min: 65, max: 120 },
      protein: { min: 3.5, max: 6.5 },
      carbs: { min: 4.0, max: 8.5 },
      fat: { min: 2.5, max: 7.5 },
    },
    dietaryFlags: 'veg',
    allergens: ['dairy'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_paneer_raw',
    name: 'Fresh Paneer (Cottage Cheese)',
    hindiName: 'ताज़ा पनीर',
    aliases: ['paneer', 'cottage cheese', 'raw paneer'],
    categoryId: 'dairy',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '50g block / 4-5 cubes',
    baseNutrition: { calories: 145, protein: 9.5, carbs: 2.1, fat: 11.2, fiber: 0 },
    allowedNutritionRange: {
      calories: { min: 120, max: 180 },
      protein: { min: 8.0, max: 13.0 },
      carbs: { min: 1.0, max: 3.5 },
      fat: { min: 8.5, max: 14.5 },
    },
    dietaryFlags: 'veg',
    allergens: ['dairy'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_toned_milk',
    name: 'Toned Cow Milk (Warm/Cold)',
    hindiName: 'दूध',
    aliases: ['milk', 'doodh', 'toned milk'],
    categoryId: 'dairy',
    servingUnit: 'glass',
    servingAmount: 1,
    servingDescription: '1 glass (approx. 200ml)',
    baseNutrition: { calories: 122, protein: 6.4, carbs: 9.8, fat: 6.0, fiber: 0 },
    allowedNutritionRange: {
      calories: { min: 95, max: 155 },
      protein: { min: 5.5, max: 8.0 },
      carbs: { min: 8.0, max: 12.0 },
      fat: { min: 3.0, max: 8.5 },
    },
    dietaryFlags: 'veg',
    allergens: ['dairy'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_chaas',
    name: 'Chaas / Spiced Buttermilk',
    hindiName: 'छाछ / मट्ठा',
    aliases: ['chaas', 'buttermilk', 'mattha'],
    categoryId: 'dairy',
    servingUnit: 'glass',
    servingAmount: 1,
    servingDescription: '1 glass (approx. 200ml)',
    baseNutrition: { calories: 42, protein: 2.2, carbs: 4.1, fat: 1.8, fiber: 0 },
    allowedNutritionRange: {
      calories: { min: 30, max: 65 },
      protein: { min: 1.5, max: 3.5 },
      carbs: { min: 2.5, max: 6.0 },
      fat: { min: 0.8, max: 3.0 },
    },
    dietaryFlags: 'veg',
    allergens: ['dairy'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },

  // ── PROTEIN & EGGS ───────────────────────────────────────────────────────
  {
    id: 'food_boiled_egg_whole',
    name: 'Whole Boiled Egg',
    hindiName: 'उबला अंडा',
    aliases: ['egg', 'boiled egg', 'whole egg', 'anda'],
    categoryId: 'protein',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 large egg (approx. 50g)',
    baseNutrition: { calories: 74, protein: 6.3, carbs: 0.4, fat: 5.0, fiber: 0 },
    allowedNutritionRange: {
      calories: { min: 65, max: 85 },
      protein: { min: 5.5, max: 7.2 },
      carbs: { min: 0.1, max: 1.0 },
      fat: { min: 4.2, max: 6.0 },
    },
    dietaryFlags: 'egg',
    allergens: ['eggs'],
    source: 'USDA FoodData Central / ICMR',
    verified: true,
    active: true,
  },
  {
    id: 'food_egg_white',
    name: 'Boiled Egg White',
    hindiName: 'अंडे की सफेदी',
    aliases: ['egg white', 'anda safedi'],
    categoryId: 'protein',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 large egg white (approx. 33g)',
    baseNutrition: { calories: 17, protein: 3.6, carbs: 0.2, fat: 0.1, fiber: 0 },
    allowedNutritionRange: {
      calories: { min: 14, max: 22 },
      protein: { min: 3.0, max: 4.5 },
      carbs: { min: 0.0, max: 0.5 },
      fat: { min: 0.0, max: 0.3 },
    },
    dietaryFlags: 'egg',
    allergens: ['eggs'],
    source: 'USDA FoodData Central',
    verified: true,
    active: true,
  },
  {
    id: 'food_egg_omelette',
    name: '2-Egg Vegetable Omelette',
    hindiName: 'आमलेट',
    aliases: ['omelette', 'omelet', 'egg omelette'],
    categoryId: 'protein',
    servingUnit: 'plate',
    servingAmount: 1,
    servingDescription: '2 eggs with onion, tomato & light oil',
    baseNutrition: { calories: 195, protein: 13.2, carbs: 3.5, fat: 14.1, fiber: 0.6 },
    allowedNutritionRange: {
      calories: { min: 160, max: 250 },
      protein: { min: 11.0, max: 16.0 },
      carbs: { min: 2.0, max: 6.0 },
      fat: { min: 11.0, max: 19.0 },
    },
    dietaryFlags: 'egg',
    allergens: ['eggs'],
    source: 'USDA FoodData Central',
    verified: true,
    active: true,
  },
  {
    id: 'food_grilled_chicken_breast',
    name: 'Grilled Chicken Breast (Skinless)',
    hindiName: 'ग्रिल्ड चिकन ब्रेस्ट',
    aliases: ['chicken breast', 'grilled chicken', 'boiled chicken breast'],
    categoryId: 'protein',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '100g cooked portion',
    baseNutrition: { calories: 165, protein: 31.0, carbs: 0, fat: 3.6, fiber: 0 },
    allowedNutritionRange: {
      calories: { min: 140, max: 200 },
      protein: { min: 27.0, max: 35.0 },
      carbs: { min: 0.0, max: 2.0 },
      fat: { min: 2.5, max: 6.0 },
    },
    dietaryFlags: 'non_veg',
    allergens: [],
    source: 'USDA FoodData Central',
    verified: true,
    active: true,
  },
  {
    id: 'food_chicken_curry',
    name: 'Homestyle Chicken Curry',
    hindiName: 'चिकन करी',
    aliases: ['chicken curry', 'murgh curry', 'tari wala chicken'],
    categoryId: 'protein',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 medium katori (approx. 160g, 2 small pieces + gravy)',
    baseNutrition: { calories: 245, protein: 22.4, carbs: 6.5, fat: 14.2, fiber: 1.4 },
    allowedNutritionRange: {
      calories: { min: 190, max: 320 },
      protein: { min: 18.0, max: 28.0 },
      carbs: { min: 4.0, max: 11.0 },
      fat: { min: 9.0, max: 20.0 },
    },
    dietaryFlags: 'non_veg',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_soya_chunks',
    name: 'Soya Chunks Curry (Cooked)',
    hindiName: 'सोया चंक्स करी',
    aliases: ['soya chunks', 'mealmaker', 'soya curry', 'soybean chunks'],
    categoryId: 'protein',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 medium katori (approx. 140g)',
    baseNutrition: { calories: 168, protein: 17.5, carbs: 12.4, fat: 4.8, fiber: 4.9 },
    allowedNutritionRange: {
      calories: { min: 130, max: 220 },
      protein: { min: 14.0, max: 22.0 },
      carbs: { min: 8.0, max: 18.0 },
      fat: { min: 2.5, max: 8.5 },
    },
    dietaryFlags: 'vegan',
    allergens: ['soy'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_whey_protein',
    name: 'Whey Protein Isolate (in Water)',
    hindiName: 'व्हे प्रोटीन',
    aliases: ['whey', 'protein powder', 'protein shake', 'whey isolate'],
    categoryId: 'protein',
    servingUnit: 'serving',
    servingAmount: 1,
    servingDescription: '1 standard scoop (approx. 30g powder in water)',
    baseNutrition: { calories: 120, protein: 25.0, carbs: 2.0, fat: 1.2, fiber: 0 },
    allowedNutritionRange: {
      calories: { min: 100, max: 140 },
      protein: { min: 23.0, max: 27.0 },
      carbs: { min: 0.5, max: 4.0 },
      fat: { min: 0.5, max: 2.5 },
    },
    dietaryFlags: 'veg',
    allergens: ['dairy'],
    source: 'USDA FoodData Central / Standard Spec',
    verified: true,
    active: true,
  },

  // ── FRUITS ───────────────────────────────────────────────────────────────
  {
    id: 'food_apple',
    name: 'Fresh Apple with Skin',
    hindiName: 'सेब',
    aliases: ['apple', 'seb'],
    categoryId: 'fruits',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 medium apple (approx. 150g)',
    baseNutrition: { calories: 78, protein: 0.4, carbs: 20.8, fat: 0.3, fiber: 3.6 },
    allowedNutritionRange: {
      calories: { min: 60, max: 105 },
      protein: { min: 0.2, max: 0.8 },
      carbs: { min: 16.0, max: 26.0 },
      fat: { min: 0.1, max: 0.6 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'USDA FoodData Central / ICMR',
    verified: true,
    active: true,
  },
  {
    id: 'food_banana',
    name: 'Fresh Banana (Medium)',
    hindiName: 'केला',
    aliases: ['banana', 'kela'],
    categoryId: 'fruits',
    servingUnit: 'piece',
    servingAmount: 1,
    servingDescription: '1 medium banana (approx. 110g peeled)',
    baseNutrition: { calories: 98, protein: 1.2, carbs: 25.4, fat: 0.3, fiber: 2.8 },
    allowedNutritionRange: {
      calories: { min: 75, max: 130 },
      protein: { min: 0.8, max: 1.8 },
      carbs: { min: 19.0, max: 32.0 },
      fat: { min: 0.1, max: 0.6 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'USDA FoodData Central / ICMR',
    verified: true,
    active: true,
  },
  {
    id: 'food_papaya',
    name: 'Fresh Papaya (Diced Cubes)',
    hindiName: 'पपीता',
    aliases: ['papaya', 'papita'],
    categoryId: 'fruits',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 medium bowl (approx. 150g)',
    baseNutrition: { calories: 62, protein: 0.9, carbs: 15.2, fat: 0.2, fiber: 2.7 },
    allowedNutritionRange: {
      calories: { min: 45, max: 85 },
      protein: { min: 0.5, max: 1.4 },
      carbs: { min: 11.0, max: 20.0 },
      fat: { min: 0.1, max: 0.5 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },

  // ── SNACKS & NUTS ────────────────────────────────────────────────────────
  {
    id: 'food_roasted_makhana',
    name: 'Roasted Makhana (Fox Nuts)',
    hindiName: 'मखाना',
    aliases: ['makhana', 'fox nuts', 'lotus seeds'],
    categoryId: 'snacks_nuts',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 medium bowl dry roasted (approx. 30g)',
    baseNutrition: { calories: 106, protein: 2.9, carbs: 23.0, fat: 0.4, fiber: 2.2 },
    allowedNutritionRange: {
      calories: { min: 85, max: 140 },
      protein: { min: 2.0, max: 4.0 },
      carbs: { min: 18.0, max: 28.0 },
      fat: { min: 0.2, max: 3.5 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_almonds',
    name: 'Raw Almonds (Badam)',
    hindiName: 'बादाम',
    aliases: ['almonds', 'badam', 'soaked almonds'],
    categoryId: 'snacks_nuts',
    servingUnit: 'piece',
    servingAmount: 10,
    servingDescription: '10 whole almonds (approx. 12g)',
    baseNutrition: { calories: 72, protein: 2.6, carbs: 2.6, fat: 6.1, fiber: 1.5 },
    allowedNutritionRange: {
      calories: { min: 60, max: 85 },
      protein: { min: 2.0, max: 3.2 },
      carbs: { min: 1.8, max: 3.2 },
      fat: { min: 5.0, max: 7.2 },
    },
    dietaryFlags: 'vegan',
    allergens: ['nuts'],
    source: 'USDA FoodData Central / ICMR',
    verified: true,
    active: true,
  },
  {
    id: 'food_roasted_chana',
    name: 'Roasted Chana (with Skin)',
    hindiName: 'भुना चना',
    aliases: ['bhuna chana', 'roasted chickpeas', 'roasted gram'],
    categoryId: 'snacks_nuts',
    servingUnit: 'bowl',
    servingAmount: 1,
    servingDescription: '1 small katori (approx. 40g)',
    baseNutrition: { calories: 148, protein: 8.2, carbs: 24.5, fat: 2.2, fiber: 6.8 },
    allowedNutritionRange: {
      calories: { min: 120, max: 180 },
      protein: { min: 6.5, max: 10.5 },
      carbs: { min: 19.0, max: 30.0 },
      fat: { min: 1.4, max: 3.5 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },

  // ── BEVERAGES ────────────────────────────────────────────────────────────
  {
    id: 'food_chai_milk',
    name: 'Indian Masala Chai (with Milk & Light Sugar)',
    hindiName: 'चाय',
    aliases: ['chai', 'tea', 'masala tea', 'milk tea'],
    categoryId: 'beverages',
    servingUnit: 'cup',
    servingAmount: 1,
    servingDescription: '1 small cup (approx. 120ml)',
    baseNutrition: { calories: 75, protein: 2.4, carbs: 9.8, fat: 2.8, fiber: 0 },
    allowedNutritionRange: {
      calories: { min: 45, max: 120 },
      protein: { min: 1.5, max: 3.5 },
      carbs: { min: 5.0, max: 16.0 },
      fat: { min: 1.5, max: 4.5 },
    },
    dietaryFlags: 'veg',
    allergens: ['dairy'],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
  {
    id: 'food_black_coffee',
    name: 'Black Coffee (Unsweetened)',
    hindiName: 'ब्लैक कॉफ़ी',
    aliases: ['coffee', 'black coffee', 'espresso'],
    categoryId: 'beverages',
    servingUnit: 'cup',
    servingAmount: 1,
    servingDescription: '1 cup (approx. 150ml)',
    baseNutrition: { calories: 3, protein: 0.2, carbs: 0.4, fat: 0.0, fiber: 0 },
    allowedNutritionRange: {
      calories: { min: 1, max: 10 },
      protein: { min: 0.0, max: 0.5 },
      carbs: { min: 0.0, max: 1.0 },
      fat: { min: 0.0, max: 0.1 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'USDA FoodData Central',
    verified: true,
    active: true,
  },
  {
    id: 'food_coconut_water',
    name: 'Tender Coconut Water',
    hindiName: 'नारियल पानी',
    aliases: ['nariyal pani', 'coconut water'],
    categoryId: 'beverages',
    servingUnit: 'glass',
    servingAmount: 1,
    servingDescription: '1 glass (approx. 240ml)',
    baseNutrition: { calories: 45, protein: 1.7, carbs: 9.0, fat: 0.5, fiber: 2.6 },
    allowedNutritionRange: {
      calories: { min: 35, max: 65 },
      protein: { min: 1.0, max: 2.5 },
      carbs: { min: 7.0, max: 13.0 },
      fat: { min: 0.2, max: 1.0 },
    },
    dietaryFlags: 'vegan',
    allergens: [],
    source: 'ICMR - National Institute of Nutrition (IFCT)',
    verified: true,
    active: true,
  },
];
